# 第九次作业

1、采用numpy中的内置函数实现斗地主的发牌

In [3]:
class Card():
      RANKS = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]  
      SUITS = ["梅","方","红","黑"]  
      def __init__(self,rank,suit,face_up=True):
          self.rank = rank
          self.suit = suit
          self.is_face_up = face_up         
      def __str__(self):
          if self.is_face_up:
             rep = self.suit+self.rank
          else:
             rep = "XX"
          return rep
      def pic_order(self):
          if self.rank == "A":
             Facenum = 1
          elif self.rank == "J":
             Facenum = 11
          elif self.rank == "Q":
             Facenum = 12
          elif self.rank == "K":
             Facenum = 13
          else:
             Facenum = int(self.rank)
          if self.suit =="梅":
             Suit=1
          elif self.suit =="方":
             Suit=2
          elif self.suit =="红":
             Suit=3
          else:
             Suit=4
          return (Suit-1)*13 +Facenum
      def flip(self):                 
          self.is_face_up = not self.is_face_up
          
class Hand():
      def __init__(self):
          self.cards = []        
      def __str__(self):         
          if self.cards:
             rep = ""
             for card in self.cards:
                 rep += str(card) + "\t"
          else:
             rep = "无牌"
          return rep
      def clear(self):
          self.cards = []
      def add(self,card):
          self.cards.append(card)
      def give(self,card,other_hand):
          self.cards.remove(card)
          other_hand.add(card)
          
class Poke(Hand):
      def populate(self):            
          for suit in Card.SUITS:
              for rank in Card.RANKS:
                  self.add(Card(rank,suit))
      def shuffle(self):
          import random
          random.shuffle(self.cards)     
      def deal(self,hands,per_hand = 13): 
          for rounds in range(per_hand):
              for hand in hands:
                  if self.cards:
                     top_card = self.cards[0]
                     self.give(top_card,hand)  
                  else:
                     print("牌已经发完")
                     
if __name__ == "__main__":
     players = [Hand(),Hand(),Hand(),Hand()]
     pokel = Poke()
     pokel.populate()             
     pokel.shuffle()              
     pokel.deal(players,13)       
     n=1
     for hand in players:
         print("牌手",n,end=":")
         print(hand)
         n=n+1
     input("\n按回车键退出")

牌手 1:方J	红J	梅3	红2	梅7	方7	红9	梅10	红K	红6	红7	黑J	方4	
牌手 2:方3	红3	梅4	黑8	红4	黑Q	黑6	梅6	方2	方6	红Q	梅5	梅8	
牌手 3:黑4	黑9	黑2	梅A	方10	红10	方8	梅2	梅9	黑5	黑K	黑10	方A	
牌手 4:黑A	红A	黑3	方9	黑7	梅K	梅J	方5	梅Q	红5	方K	方Q	红8	

按回车键退出


2、简述numpy中数据存取的形式并实现

（1）、一维或二维数据

In [11]:
import numpy as np
x=np.ones((2,4))
np.savetxt('x',x,fmt='%1.4e',delimiter=',')
np.loadtxt('x',delimiter=',')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
import numpy as np
x=np.arange(10)
np.save('x',x)
np.load('x.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

（2）、多维数据

In [29]:
import numpy as np
x=np.arange(100).reshape(5,10,2)
x.tofile('a.dat',sep=',',format='%d')
np.fromfile('a.dat',sep=',',dtype=np.int_).reshape(5,10,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])